### ISSUE TITLE
Address "Related Systems" tab not functioning properly in the websites modal

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#110]
In the websites modal (e.g. https://stage.ea.gsa.gov/#/websites/1), when you click on the "Related Systems" tab, it appends the related systems table at the very bottom of the Overview tab, rather than switching over and only displaying the related systems tab. 

I believe this may be an issue with the src/app/components/modals/websites-modal/websites-modal.component.ts file, but I cannot pinpoint where the issue is.

**Comment by mvogelgesang** [comment]
closing, merged via PR #118
