### ISSUE TITLE
Upgrade Angular from v14 to v15

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#116]
As part of routine updates to Angular

**Comment by hatfieldjm4** [comment]
Need to upgrade Typescript and NodeJS in order to upgrade from v14 to v15. 
#115 and #122

**Comment by hatfieldjm4** [comment]
I noticed that @angular/cdk was still running version 14.2.7 when I checked the Angular version (npm run ng version). To upgrade cdk, I used the following command: 
npm run ng update @angular/cdk@15.1.1
Received the following error: 
While resolving: @ng-select/ng-select@9.1.0
To resolve [this](https://www.npmjs.com/package/@ng-select/ng-select), I executed: npm install @ng-select/ng-select@10.0.3 (which resolved the error).

**Comment by hatfieldjm4** [comment]
I upgraded to Angular 15 in the [angular15 branch](https://github.com/GSA/GEAR3/tree/angular15).

**Comment by mvogelgesang** [comment]
thanks for the heads up @hatfieldjm4
