### ISSUE TITLE
Create a PDF in-page view of the GSA strategic plan under the "IT Strategic Framework" link

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#182]
In dev GEAR, when you click on the left-hand side IT Strategy -> IT Strategic Framework, it displays a link instructing the user to "Download Full GSA IT Strategic Plan" with a hyperlink. I received customer feedback that it would be better if [this PDF](https://www.gsa.gov/system/files/GSA_Strategic_Plan_FY_2022_-_2026_FINAL_508.pdf) were displayed in the page view itself, similar to how the [EA View](https://dev1.ea.gsa.gov/#/ea_view) embeds the PDF (get to EA view by clicking on the left-hand side Enterprise Architecture -> EA View) currently on the site.

**Comment by kinggsagov** [comment]
This was merged to master
