### ISSUE TITLE
Remove or change file path at the top of Strategic Framework pdf view

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#203]
On the [Strategic Framework view](https://dev.ea.gsa.gov/#/strategic_framework), there is a file path listed at the top that references a previous developer. This either needs to be removed (ideal) or changed to a different file path (less ideal).

**Comment by kinggsagov** [comment]
[GSA IT Strategic Framework.pdf](https://github.com/GSA/GEAR3/files/14043568/GSA.IT.Strategic.Framework.pdf)
use the updated pdf
