### ISSUE TITLE
Tab/enter in the "GEAR Navigation" (top navbar) is not closing the nav menu for GEAR Navigation

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#224]
We noticed this in our session with Dan to review the top navbar accessibility

**Comment by kinggsagov** [comment]
224-GEAR-Navigation-Fix-for-Tab-Enter is the branch

**Comment by kinggsagov** [comment]
$(document).ready(() => {
      // Close dropdown when clicking
      $(document).on('click', (event) => {
        if ($('.dropdown.show').length) {
          $('.dropdown.show').removeClass('show');
        }
      });

      // Close dropdown when key-entering any link within the dropdown menu
      $(document).on('keydown', (event) => {
        if (event.key === 'Enter' && $('.dropdown.show').length) {
          $('.dropdown.show').removeClass('show');
        }
      });
    });
