### ISSUE TITLE
Add RITM field to obj_technology 

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#228]
This would need to be added to the IT standards report (i.e. the list view), modal, and user form. Please place this above the comments field in the modal and the user form.  varchar(200)
RITM (Requested Item)

**Comment by hatfieldjm4** [comment]
Please add it to the API documentation as well with this definition: 
Request Items (RITMs) contain the actual form the customer submitted and links to one or more tasks required for fulfillment. RITMs can be assigned to a fulfillment group, not an individual.

**Comment by kinggsagov** [comment]
Use gear_schema;
ALTER TABLE obj_technology
ADD COLUMN RITM varchar(200)
