### ISSUE TITLE
A trigger is needed to automatically update the EoL (end of life) date on an existing entry in obj_technology if the EoL date changes in the tech_catalog schema

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#269]
If the EoL date changes in the tp_SoftwareLifecycle table, there is currently no way that it gets updated in the obj_technology.endOfLifeDate field. We should place a trigger, I think, on the tech_catalog.tp_SoftwareLifecycle to update obj_technology.endOfLifeDate based on any changes to the tp_SoftwareLifecycle.endOfLifeDate data field. 

This would be very similar to the trigger that is already set up on the tp_SoftwareVersion table to update obj_technology.SoftwareVersionName based on any changes to the version name. You should be able to use this example to create the trigger on the tp_SoftwareLifecycle table.

**Comment by khgsa** [comment]
CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `endOfLifeDate_update_trg` AFTER UPDATE ON `tp_SoftwareLifecycle` FOR EACH ROW BEGIN
     IF OLD.endOfLifeDate <> NEW.endOfLifeDate THEN
         UPDATE gear_schema.obj_technology
            SET endOfLifeDate = NEW.endOfLifeDate
    WHERE softwareVersion = NEW.id;
     END IF;
 END

**Comment by hatfieldjm4** [comment]
While testing this trigger, if you make any changes to tech_catalog please make sure to revert them back to the original values when you are done testing. The dev version of tech_catalog has been more reliably updated vs the one on the prod side due to the stage timeouts (which I'm hoping do not happen on the prod URL)

**Comment by hatfieldjm4** [comment]
CREATE DEFINER=``GEAR2_ODS``@``%`` TRIGGER ``endOfLifeDate_update_trg`` AFTER UPDATE ON ``tp_SoftwareLifecycle`` FOR EACH ROW BEGIN
IF OLD.endOfLifeDate <> NEW.endOfLifeDate THEN
UPDATE gear_schema.obj_technology
SET endOfLifeDate = NEW.endOfLifeDate
WHERE softwareLifecycleId = NEW.id;
END IF;
END

**Comment by khgsa** [comment]
```sql
DELIMITER $$
CREATE DEFINER = `GEAR2_ODS`@`%` TRIGGER `tech_catalog`.`tp_endOfLifeDate_update_trg` AFTER UPDATE ON `tp_SoftwareLifecycle` FOR EACH ROW
BEGIN
IF NOT (OLD.endOfLifeDate <=> NEW.endOfLifeDate) THEN
		UPDATE gear_schema.obj_technology
			SET endOfLifeDate = NEW.endOfLifeDate
            WHERE softwareRelease = NEW.softwareRelease;
	END IF;
END $$
```

**Comment by khgsa** [comment]
**tp_Manufacturer**

_AFTER UPDATE_

> CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `manufacturer_update_trg` AFTERUPDATE ON `tp_Manufacturer` FOR EACH ROW BEGIN
> 	IF OLD.name <> NEW.name THEN
> 		UPDATE gear_schema.obj_technology
> 			SET manufacturerName = NEW.name
> 					WHERE manufacturer = NEW.id;
> 	ENDIF;
> END
```
CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `manufacturer_update_trg` AFTERUPDATE ON `tp_Manufacturer` FOR EACH ROW BEGIN
	IF NOT (OLD.name <=> NEW.name) THEN
		UPDATE gear_schema.obj_technology
			SET manufacturerName = NEW.name
	        WHERE manufacturer = NEW.id;
	ENDIF;
END
```

**tp_SoftwareProduct**
_AFTER UPDATE_

> CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `softwareProduct_update_trg` AFTERUPDATE ON `tp_SoftwareProduct` FOR EACH ROW BEGIN
> 	IF OLD.name <> NEW.name THEN
> 		UPDATE gear_schema.obj_technology
> 			SET softwareProductName = NEW.name
> 			WHERE softwareProduct = NEW.id;
> 	ENDIF;
> END
```
CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `softwareProduct_update_trg` AFTERUPDATE ON `tp_SoftwareProduct` FOR EACH ROW BEGIN
	IF NOT (OLD.name <=> NEW.name) THEN
		UPDATE gear_schema.obj_technology
			SET softwareProductName = NEW.name
			WHERE softwareProduct = NEW.id;
	ENDIF;
END
```

**tp_SoftwareRelease**
_AFTER UPDATE_

> CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `softwareRelease_update_trg` AFTERUPDATE ON `tp_SoftwareRelease` FOR EACH ROW BEGIN
> 	IF OLD.application <> NEW.application THEN
> 		UPDATE gear_schema.obj_technology
> 			SET softwareReleaseName = NEW.application
> 			WHERE softwareRelease = NEW.id;
> 	ENDIF;
> END

```
CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `softwareRelease_update_trg` AFTERUPDATE ON `tp_SoftwareRelease` FOR EACH ROW BEGIN
	IF NOT (OLD.application <=> NEW.application) THEN
		UPDATE gear_schema.obj_technology
			SET softwareReleaseName = NEW.application
			WHERE softwareRelease = NEW.id;
	ENDIF;
END
```

**tp_SoftwareVersion**
_AFTER UPDATE_

> CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `softwareVersion_update_trg` AFTERUPDATE ON `tp_SoftwareVersion` FOR EACH ROW BEGIN
> 	IF OLD.name <> NEW.name THEN
> 		UPDATE gear_schema.obj_technology
> 			SET softwareVersionName = NEW.name
> 			WHERE softwareVersion = NEW.id;
> 	ENDIF;
> END
```
CREATE DEFINER=`GEAR2_ODS`@`%` TRIGGER `softwareVersion_update_trg` AFTERUPDATE ON `tp_SoftwareVersion` FOR EACH ROW BEGIN
	IF NOT (OLD.name <=> NEW.name) THEN
		UPDATE gear_schema.obj_technology
			SET softwareVersionName = NEW.name
			WHERE softwareVersion = NEW.id;
	ENDIF;
END
```

**Comment by hatfieldjm4** [comment]
@khgsa I've made the changes in the dev database based on your suggestions below the gray text for each tech_catalog table mentioned.
