### ISSUE TITLE
Improve the UX of the capabilities model to improve readability of the description 

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#302]
The call out boxes size need to be adjusted on the [capabilities model](https://dev.ea.gsa.gov/#/capabilities_model). It’s hard to read the descriptive information, especially on smaller displays like laptop screens.

**Comment by kinggsagov** [comment]
class="row card-body overflow-auto"

**Comment by kinggsagov** [comment]
Can't resolve 'node_modules/tableexport.jquery.plugin/libs/es6-promise/es6-promise.auto.min.js' in 'C:\kingwork\GEAR3'
