### ISSUE TITLE
In the business systems modal, change the text that appears if no matching record exists in the "Records" tab

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#348]
When you go to the Business Systems & Subsystems report and click on an individual system (which opens up the modal), there is a "Records" tab that appears in the modal. If the system currently does not have any record tied to it, then it will display, "No matching records." The Records Management team would prefer this to read "Contact Records Management (records@gsa.gov) for a more detailed analysis of records associated with this system."

**Comment by kinggsagov** [comment]
C:\kingwork\dev_GEAR3\GEAR3\.angular\cache\16.2.13\angular-webpack\85f514873fe733ca46638b293b0bcf7712faa8d3\1.pack (1 hit)
	Line 1665560: ngOnInit(){this.modalService.currentSys.subscribe(e=>this.system=e),$("#sysTimeTable").bootstrapTable($.extend(this.sysTimeTableOptions,{columns:this.sysTimecolumnDefs,data:[]})),$("#systemCapTable").bootstrapTable($.extend(this.sysCapTableOptions,{columns:this.sysCapColumnDefs,data:[]})),$("#systemInvestTable").bootstrapTable($.extend(this.sysInvestTableOptions,{columns:this.sysInvestColumnDefs,data:[]})),$("#systemTechTable").bootstrapTable($.extend(this.sysTechTableOptions,{columns:this.sysTechColumnDefs,data:[]})),$("#systemRecTable").bootstrapTable($.extend(this.sysRecTableOptions,{columns:this.sysRecColumnDefs,data:[]})),$("#systemWebsitesTable").bootstrapTable($.extend(this.sysWebsitesTableOptions,{columns:this.sysWebsitesColumnDefs,data:[]})),$(document).ready($("#systemCapTable").on("click-row.bs.table",function(e,i){$("#systemDetail").modal("hide"),this.tableService.capsTableClick(i)}.bind(this))),$(document).ready($("#systemTechTable").on("click-row.bs.table",function(e,i){$("#systemDetail").modal("hide"),this.tableService.itStandTableClick(i)}.bind(this))),$(document).ready($("#systemInvestTable").on("click-row.bs.table",function(e,i){$("#systemDetail").modal("hide"),this.tableService.investTableClick(i)}.bind(this))),$(document).ready($("#systemRecTable").on("click-row.bs.table",function(e,i){$("#systemDetail").modal("hide"),this.tableService.recordsTableClick(i)}.bind(this))),$(document).ready($("#systemWebsitesTable").on("click-row.bs.table",function(e,i){$("#systemDetail").modal("hide"),this.tableService.websitesTableClick(i)}.bind(this))),$("#systemDetail").on("hidden.bs.modal",function(e){$("#systemTabs li:first-child a").tab("show"),this.sharedService.removeIDfromURL()}.bind(this))}systemEdit(){$("#systemDetail").modal("hide"),this.modalService.updateDetails(this.system,"system",!1),this.sharedService.setSystemForm(),$("#systemManager").modal("show")}static#e=this.\u0275fac=function(i){return new(i||t)(Y(Nn),Y(Sn),Y(en),Y(tn),Y(yn))};static#t=this.\u0275cmp=lt({type:t,sele ...
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\dist\bootstrap-table-locale-all.js (1 hit)
	Line 2225: 	    return 'No matching records found';
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\dist\bootstrap-table-locale-all.min.js (1 hit)
	Line 10: !function(t,n){"object"==typeof exports&&"undefined"!=typeof module?n(require("jquery")):"function"==typeof define&&define.amd?define(["jquery"],n):n((t="undefined"!=typeof globalThis?globalThis:t||self).jQuery)}(this,(function(t){"use strict";var n="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},r=function(t){return t&&t.Math==Math&&t},o=r("object"==typeof globalThis&&globalThis)||r("object"==typeof window&&window)||r("object"==typeof self&&self)||r("object"==typeof n&&n)||function(){return this}()||Function("return this")(),e={},a=function(t){try{return!!t()}catch(t){return!0}},i=!a((function(){return 7!=Object.defineProperty({},1,{get:function(){return 7}})[1]})),c=!a((function(){var t=function(){}.bind();return"function"!=typeof t||t.hasOwnProperty("prototype")})),u=c,f=Function.prototype.call,l=u?f.bind(f):function(){return f.apply(f,arguments)},s={},m={}.propertyIsEnumerable,g=Object.getOwnPropertyDescriptor,h=g&&!m.call({1:2},1);s.f=h?function(t){var n=g(this,t);return!!n&&n.enumerable}:m;var d,p,S=function(t,n){return{enumerable:!(1&t),configurable:!(2&t),writable:!(4&t),value:n}},w=c,P=Function.prototype,T=P.call,b=w&&P.bind.bind(T,T),R=w?b:function(t){return function(){return T.apply(t,arguments)}},C=R,v=C({}.toString),A=C("".slice),x=function(t){return A(v(t),8,-1)},O=a,y=x,F=Object,k=R("".split),M=O((function(){return!F("z").propertyIsEnumerable(0)}))?function(t){return"String"==y(t)?k(t,""):F(t)}:F,H=function(t){return null==t},j=H,E=TypeError,N=function(t){if(j(t))throw E("Can't call method on "+t);return t},D=M,z=N,L=function(t){return D(z(t))},B="object"==typeof document&&document.all,U={all:B,IS_HTMLDDA:void 0===B&&void 0!==B},Z=U.all,J=U.IS_HTMLDDA?function(t){return"function"==typeof t||t===Z}:function(t){return"function"==typeof t},G=J,I=U.all,V=U.IS_HTMLDDA?function(t){return"object"==typeof t?null!==t:G(t)||t===I}:function(t){return"object"==typeof t?null!==t:G(t)},q=o,K=J,W=functi ...
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\dist\bootstrap-table.js (1 hit)
	Line 5266:       return 'No matching records found';
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\dist\bootstrap-table.min.js (1 hit)
	Line 10: !function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e(require("jquery")):"function"==typeof define&&define.amd?define(["jquery"],e):(t="undefined"!=typeof globalThis?globalThis:t||self).BootstrapTable=e(t.jQuery)}(this,(function(t){"use strict";function e(t){return e="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t},e(t)}function i(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}function n(t,e){for(var i=0;i<e.length;i++){var n=e[i];n.enumerable=n.enumerable||!1,n.configurable=!0,"value"in n&&(n.writable=!0),Object.defineProperty(t,(o=n.key,r=void 0,"symbol"==typeof(r=function(t,e){if("object"!=typeof t||null===t)return t;var i=t[Symbol.toPrimitive];if(void 0!==i){var n=i.call(t,e||"default");if("object"!=typeof n)return n;throw new TypeError("@@toPrimitive must return a primitive value.")}return("string"===e?String:Number)(t)}(o,"string"))?r:String(r)),n)}var o,r}function o(t,e,i){return e&&n(t.prototype,e),i&&n(t,i),Object.defineProperty(t,"prototype",{writable:!1}),t}function r(t,e){return function(t){if(Array.isArray(t))return t}(t)||function(t,e){var i=null==t?null:"undefined"!=typeof Symbol&&t[Symbol.iterator]||t["@@iterator"];if(null!=i){var n,o,r,a,s=[],l=!0,c=!1;try{if(r=(i=i.call(t)).next,0===e){if(Object(i)!==i)return;l=!1}else for(;!(l=(n=r.call(i)).done)&&(s.push(n.value),s.length!==e);l=!0);}catch(t){c=!0,o=t}finally{try{if(!l&&null!=i.return&&(a=i.return(),Object(a)!==a))return}finally{if(c)throw o}}return s}}(t,e)||s(t,e)||function(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}()}function a(t){return function(t){if(Array.isArray(t))return l(t)}(t)||function(t){if("undefined"!=typeof Symbol&&null!=t[Symbol.iterator]||null!=t["@@iterator"])return Array.f ...
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\dist\locale\bootstrap-table-en-US.js (1 hit)
	Line 1367: 	    return 'No matching records found';
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\dist\locale\bootstrap-table-en-US.min.js (1 hit)
	Line 10: !function(t,n){"object"==typeof exports&&"undefined"!=typeof module?n(require("jquery")):"function"==typeof define&&define.amd?define(["jquery"],n):n((t="undefined"!=typeof globalThis?globalThis:t||self).jQuery)}(this,(function(t){"use strict";var n="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},r=function(t){return t&&t.Math==Math&&t},e=r("object"==typeof globalThis&&globalThis)||r("object"==typeof window&&window)||r("object"==typeof self&&self)||r("object"==typeof n&&n)||function(){return this}()||Function("return this")(),o={},i=function(t){try{return!!t()}catch(t){return!0}},u=!i((function(){return 7!=Object.defineProperty({},1,{get:function(){return 7}})[1]})),c=!i((function(){var t=function(){}.bind();return"function"!=typeof t||t.hasOwnProperty("prototype")})),a=c,f=Function.prototype.call,l=a?f.bind(f):function(){return f.apply(f,arguments)},s={},p={}.propertyIsEnumerable,g=Object.getOwnPropertyDescriptor,b=g&&!p.call({1:2},1);s.f=b?function(t){var n=g(this,t);return!!n&&n.enumerable}:p;var y,h,m=function(t,n){return{enumerable:!(1&t),configurable:!(2&t),writable:!(4&t),value:n}},d=c,v=Function.prototype,w=v.call,S=d&&v.bind.bind(w,w),O=d?S:function(t){return function(){return w.apply(t,arguments)}},j=O,P=j({}.toString),T=j("".slice),A=function(t){return T(P(t),8,-1)},E=i,C=A,x=Object,F=O("".split),R=E((function(){return!x("z").propertyIsEnumerable(0)}))?function(t){return"String"==C(t)?F(t,""):x(t)}:x,M=function(t){return null==t},D=M,I=TypeError,L=function(t){if(D(t))throw I("Can't call method on "+t);return t},k=R,N=L,H=function(t){return k(N(t))},_="object"==typeof document&&document.all,z={all:_,IS_HTMLDDA:void 0===_&&void 0!==_},G=z.all,U=z.IS_HTMLDDA?function(t){return"function"==typeof t||t===G}:function(t){return"function"==typeof t},q=U,B=z.all,W=z.IS_HTMLDDA?function(t){return"object"==typeof t?null!==t:q(t)||t===B}:function(t){return"object"==typeof t?null!==t:q(t)},J=e,K=U,Q=functi ...
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\src\constants\index.js (1 hit)
	Line 385:     return 'No matching records found'
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\bootstrap-table\src\locale\bootstrap-table-en-US.js (1 hit)
	Line  45:     return 'No matching records found'
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\typescript\lib\lib.dom.d.ts (4 hits)
	Line  8779:      * If successful, request's result will be an IDBCursorWithValue, or null if there were no matching records.
	Line  8785:      * If successful, request's result will be an IDBCursor, or null if there were no matching records.
	Line  8902:      * If successful, request's result will be an IDBCursorWithValue pointing at the first matching record, or null if there were no matching records.
	Line  8908:      * If successful, request's result will be an IDBCursor pointing at the first matching record, or null if there were no matching records.
  C:\kingwork\dev_GEAR3\GEAR3\node_modules\typescript\lib\lib.webworker.d.ts (4 hits)
	Line 2033:      * If successful, request's result will be an IDBCursorWithValue, or null if there were no matching records.
	Line 2039:      * If successful, request's result will be an IDBCursor, or null if there were no matching records.
	Line 2156:      * If successful, request's result will be an IDBCursorWithValue pointing at the first matching record, or null if there were no matching records.
	Line 2162:      * If successful, request's result will be an IDBCursor pointing at the first matching record, or null if there were no matching records.
  C:\kingwork\dev_GEAR3\GEAR3\public\scripts.66d010e7972149d1.js (1 hit)
	Line   1: !function(j,G4){"use strict";"object"==typeof module&&"object"==typeof module.exports?module.exports=j.document?G4(j,!0):function(t3){if(!t3.document)throw new Error("jQuery requires a window with a document");return G4(t3)}:G4(j)}(typeof window<"u"?window:this,function(j,G4){"use strict";var t3=[],K=Object.getPrototypeOf,F4=t3.slice,L2=t3.flat?function(A){return t3.flat.call(A)}:function(A){return t3.concat.apply([],A)},V1=t3.push,Z1=t3.indexOf,W={},f1=W.toString,t2=W.hasOwnProperty,P1=t2.toString,$1=P1.call(Object),O1={},r1=function(A){return"function"==typeof A&&"number"!=typeof A.nodeType&&"function"!=typeof A.item},v1=function(A){return null!=A&&A===A.window},a1=j.document,c1={type:!0,src:!0,nonce:!0,noModule:!0};function _(A,b,k){var Q,o1,y1=(k=k||a1).createElement("script");if(y1.text=A,b)for(Q in c1)(o1=b[Q]||b.getAttribute&&b.getAttribute(Q))&&y1.setAttribute(Q,o1);k.head.appendChild(y1).parentNode.removeChild(y1)}function N(A){return null==A?A+"":"object"==typeof A||"function"==typeof A?W[f1.call(A)]||"object":typeof A}var C=function(A,b){return new C.fn.init(A,b)};function F1(A){var b=!!A&&"length"in A&&A.length,k=N(A);return!r1(A)&&!v1(A)&&("array"===k||0===b||"number"==typeof b&&0<b&&b-1 in A)}C.fn=C.prototype={jquery:"3.6.4",constructor:C,length:0,toArray:function(){return F4.call(this)},get:function(A){return null==A?F4.call(this):A<0?this[A+this.length]:this[A]},pushStack:function(A){var b=C.merge(this.constructor(),A);return b.prevObject=this,b},each:function(A){return C.each(this,A)},map:function(A){return this.pushStack(C.map(this,function(b,k){return A.call(b,k,b)}))},slice:function(){return this.pushStack(F4.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},even:function(){return this.pushStack(C.grep(this,function(A,b){return(b+1)%2}))},odd:function(){return this.pushStack(C.grep(this,function(A,b){return b%2}))},eq:function(A){var b=this.length,k=+A+(A<0?b:0);return this.pushStack(0<=k&&k<b?[this[k]]:[])},end:function(){return  ...

**Comment by kinggsagov** [comment]
CUINo matching records found
      
      
      
      
       
            
            
            
            
            
             Domain Office
