### ISSUE TITLE
Update Prod GEAR Google Analytics

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#360]
Please make sure the Google analytics are reporting properly on the new launch of prod GEAR

**Comment by hatfieldjm4** [comment]
I believe it is running properly in the [Dev GA4 GEAR3 dashboard](https://analytics.google.com/analytics/web/#/p420269685/realtime/overview?params=_u..pageSize%3D25%26_u..nav%3Dmaui&collectionId=life-cycle). Would you please confirm @kinggsagov ?

**Comment by kinggsagov** [comment]
Change to use following on index.html


<script async src="https://www.googletagmanager.com/gtag/js?id=G-PDPL5T61V1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-PDPL5T61V1');
</script>
