### ISSUE TITLE
Document how to upgrade ng-sidebar-v3 library to future versions of Angular

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#386]
How do we go about upgrading the [ng-sidebar-v3 library](https://www.npmjs.com/package/ng-sidebar-v3) on NPM when a new version of Angular is released?

**Comment by khgsa** [comment]
Updated  gear playbook. Added Section Upgrade ng-sidebar-v3 section. Also, Updated section Upgrading Angular
