### ISSUE TITLE
Update the GEAR Playbook to include updated Google Analytics

### ISSUE THREAD

**Issue by joshsjurik** [GSA/GEAR3#511]
- How/where we're using GA
- How we test GA
- How we push to prod

**Comment by joshsjurik** [comment]
@hatfieldjm4 
here's my addition to the playbook. let me know what you think and if you want me to change/add/remove anything.

https://docs.google.com/document/d/1MDf8hLrqORjSP6os_quxnI8LOQieE6YCjOvOwT7_IrE/edit?tab=t.0#heading=h.nnuqgn79of3e

**Comment by hatfieldjm4** [comment]
This is great, Josh. Thanks for including instructions on how to find the measurement id, as that is not very intuitive.

**Comment by joshsjurik** [comment]
Awesome, I'm closing this out then.
